// sq_torsion_test_2.fe

/* Second test of sq_tension method. */


define edge attribute sq_torsion_mark integer

quantity sqtor energy method sq_torsion

// warped disk

constraint 1
formula: x^2 + y^2 = 1

constraint 2
formula: z = x^2


vertices
1   1  0 1  constraints 1,2
2   0  1 0  constraints 1,2
3  -1  0 1  constraints 1,2
4   0 -1 0  constraints 1,2

edges
1   1  2 constraints 1,2 sq_torsion_mark 1 quantity sqtor
2   2  3 constraints 1,2 sq_torsion_mark 1 quantity sqtor
3   3  4 constraints 1,2 sq_torsion_mark 1 quantity sqtor
4   4  1 constraints 1,2 sq_torsion_mark 1 quantity sqtor

faces
1   1 2 3 4  tension 0

read

// Numnerical test of gradient formula in sq_torsion method
gogo := { 
   r;r;r;
   unset vertex constraint 1;
   unset edge constraint 1;
   unset vertex constraint 2;
   unset edge constraint 2;
   set facet tension 0;  // for test of just sqtor
   estimate on;
   m 1e-8;
   g;
}





